### ISSUE TITLE
Plugin Submission Denied

### ISSUE THREAD

**Issue by zerebos** [MsDysphoria/DiscordFont#1]
Reason:
- Causes errors when enabled and no options selected
- Feature should be opt-in to avoid spam

Feel free to close this or reach out for more info.

**Comment by MsDysphoria** [comment]
Hey there. Could you tell me about the errors you've been having? I fixed one which was causing default space width to result in undefined just now. Also what did you mean by opting in? All options are set to default and require the user to change them to take effect. Did you mean an on-off button or a confirmation before sending?
